-- MariaDB Schema Creation Script for "My Guitars" App
-- This script creates the USERS, GUITARS, and GUITAR_IMAGES tables.

-- 1. Create USERS table
CREATE TABLE IF NOT EXISTS USERS (
    id VARCHAR(36) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) DEFAULT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY UQ_USERS_EMAIL (EMAIL)
);

-- 2. Create GUITARS table
CREATE TABLE IF NOT EXISTS GUITARS (
    id VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    YEAR INT DEFAULT NULL,
    TYPE VARCHAR(256) NOT NULL,
    COLOR VARCHAR(100) DEFAULT NULL,
    SERIAL_NUMBER VARCHAR(100) DEFAULT NULL,
    `CONDITION` VARCHAR(256) NOT NULL,
    PURCHASE_PRICE DECIMAL(10,2) DEFAULT NULL,
    CURRENT_VALUE DECIMAL(10,2) DEFAULT NULL,
    NOTES LONGTEXT DEFAULT NULL,
    IMAGE_DATA LONGTEXT DEFAULT NULL,
    IMAGE_MIME_TYPE VARCHAR(100) DEFAULT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- 3. Create GUITAR_IMAGES table
CREATE TABLE IF NOT EXISTS GUITAR_IMAGES (
    id VARCHAR(36) NOT NULL,
    GUITAR_ID VARCHAR(36) NOT NULL,
    IMAGE_DATA LONGTEXT NOT NULL,
    IMAGE_MIME_TYPE VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT FK_GUITAR_IMAGES_GUITAR 
        FOREIGN KEY (GUITAR_ID) 
        REFERENCES GUITARS (id) 
        ON DELETE CASCADE
);
