-- Migration: Add password reset tokens table and user token version
-- Run after mariadb_schema.sql

-- 1. Create PASSWORD_RESET_TOKENS table
CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS (
    id VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    TOKEN_HASH VARCHAR(64) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    USED_AT DATETIME DEFAULT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX IDX_PRT_USER_ID (USER_ID),
    INDEX IDX_PRT_TOKEN_HASH (TOKEN_HASH),
    INDEX IDX_PRT_EXPIRES_AT (EXPIRES_AT),
    CONSTRAINT FK_PRT_USER
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Add TOKEN_VERSION column to USERS table
ALTER TABLE USERS ADD COLUMN TOKEN_VERSION INT NOT NULL DEFAULT 1;
