-- Migration: Add extra hardware fields to GUITARS table
-- Description: Adds PICKUP_SELECTOR, OUTPUT_JACK, FRETS, TUNERS, and FINISH_TYPE columns

ALTER TABLE GUITARS
ADD COLUMN PICKUP_SELECTOR VARCHAR(256) DEFAULT NULL AFTER CONTROLS,
ADD COLUMN OUTPUT_JACK VARCHAR(256) DEFAULT NULL AFTER PICKUP_SELECTOR,
ADD COLUMN FRETS VARCHAR(256) DEFAULT NULL AFTER OUTPUT_JACK,
ADD COLUMN TUNERS VARCHAR(256) DEFAULT NULL AFTER FRETS,
ADD COLUMN FINISH_TYPE VARCHAR(256) DEFAULT NULL AFTER TUNERS;

-- Run this script in your production database client
