-- Migration: Add AMPS and AMP_IMAGES tables
-- Description: Adds amp collection support alongside the existing guitar collection

CREATE TABLE IF NOT EXISTS AMPS (
    id VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    YEAR INT DEFAULT NULL,
    TYPE VARCHAR(256) NOT NULL,
    COLOR VARCHAR(100) DEFAULT NULL,
    SERIAL_NUMBER VARCHAR(100) DEFAULT NULL,
    `CONDITION` VARCHAR(256) NOT NULL,
    WATTAGE VARCHAR(256) DEFAULT NULL,
    CHANNELS VARCHAR(256) DEFAULT NULL,
    PREAMP_TUBES VARCHAR(256) DEFAULT NULL,
    POWER_TUBES VARCHAR(256) DEFAULT NULL,
    RECTIFIER VARCHAR(256) DEFAULT NULL,
    OUTPUT_TRANSFORMER VARCHAR(256) DEFAULT NULL,
    SPEAKER_BRAND VARCHAR(256) DEFAULT NULL,
    SPEAKER_MODEL VARCHAR(256) DEFAULT NULL,
    SPEAKER_SIZE VARCHAR(256) DEFAULT NULL,
    SPEAKER_COUNT VARCHAR(256) DEFAULT NULL,
    IMPEDANCE VARCHAR(256) DEFAULT NULL,
    CABINET_MATERIAL VARCHAR(256) DEFAULT NULL,
    BAFFLE VARCHAR(256) DEFAULT NULL,
    FINISH_TYPE VARCHAR(256) DEFAULT NULL,
    MADE_IN VARCHAR(256) DEFAULT NULL,
    CONTROLS VARCHAR(256) DEFAULT NULL,
    BUILT_IN_EFFECTS VARCHAR(256) DEFAULT NULL,
    EFFECTS_LOOP VARCHAR(256) DEFAULT NULL,
    FOOTSWITCH VARCHAR(256) DEFAULT NULL,
    INPUTS VARCHAR(256) DEFAULT NULL,
    OUTPUTS VARCHAR(256) DEFAULT NULL,
    NOTES LONGTEXT DEFAULT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS AMP_IMAGES (
    id VARCHAR(36) NOT NULL,
    AMP_ID VARCHAR(36) NOT NULL,
    IMAGE_DATA LONGTEXT NOT NULL,
    IMAGE_MIME_TYPE VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT FK_AMP_IMAGES_AMP
        FOREIGN KEY (AMP_ID)
        REFERENCES AMPS (id)
        ON DELETE CASCADE
);

-- Run this script in your production database client
