-- Migration Script to add 11 new specification fields to the GUITARS table
-- Run this on your production or staging database to apply the changes without losing data.

ALTER TABLE `GUITARS` 
ADD COLUMN `BODY` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `TOP` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `NECK` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `FRETBOARD` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `BRIDGE` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `NUT` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `NECK_PICKUP` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `MIDDLE_PICKUP` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `BRIDGE_PICKUP` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `CONTROLS` VARCHAR(256) DEFAULT NULL,
ADD COLUMN `MADE_IN` VARCHAR(256) DEFAULT NULL;
